### ISSUE TITLE
Encode F# collections

### ISSUE THREAD

**Issue by Tarmil** [Tarmil/FSharp.SystemTextJson#17]
We should encode F# collections in a way that makes sense.

* `list<'T>` as a JSON array.

* `Set<'T>` as a JSON array.

* `Map<string, 'V>` as a JSON object.

* `Map<'K, 'V>` when `'K <> string` as an array of 2-valued arrays (key-value pairs).

**Comment by baronfel** [comment]
FYI lists and sets are handled correctly already:

```fsharp
// Learn more about F# at http://fsharp.org

open System
open System.Text.Json

type Thing = 
    { Index: int }

let l1 = List.init 10 (fun i -> { Index = i })


[<EntryPoint>]
let main argv =
    printfn "List: %s" (JsonSerializer.Serialize(l1))
    printfn "Set: %s" (JsonSerializer.Serialize(Seq.ofList l1))
    printfn "Map<string,'a>: %s" (JsonSerializer.Serialize (Map.ofList (l1 |> List.map (fun l -> string l.Index, l))))
    printfn "Map<complex, 'a>: %s" (JsonSerializer.Serialize (Map.ofList (l1 |> List.map (fun l -> l, l))))
    0 // return an integer exit code
```

output:
```
List: [{"Index":0},{"Index":1},{"Index":2},{"Index":3},{"Index":4},{"Index":5},{"Index":6},{"Index":7},{"Index":8},{"Index":9}]
Set: [{"Index":0},{"Index":1},{"Index":2},{"Index":3},{"Index":4},{"Index":5},{"Index":6},{"Index":7},{"Index":8},{"Index":9}]
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'mkIEnumerator@408[System.String,Program+Thing]' to type 'System.Collections.IDictionaryEnumerator'.
   at System.Text.Json.JsonSerializer.HandleDictionary(JsonClassInfo elementClassInfo, JsonSerializerOptions options, Utf8JsonWriter writer, WriteStack& state)
   at System.Text.Json.JsonSerializer.Write(Utf8JsonWriter writer, Int32 originalWriterDepth, Int32 flushThreshold, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore(Utf8JsonWriter writer, PooledByteBufferWriter output, Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteCore(PooledByteBufferWriter output, Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteCoreString(Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at Program.main(String[] argv) in /Users/chethusk/oss/fsharpjson/Program.fs:line 16
```

Maps are the odd one out.

**Comment by Tarmil** [comment]
Oh, I'm guessing it's because of built-in support for IEnumerable? Still, deserialization doesn't work :)

**Comment by mbuhot** [comment]
Here's a gist that seems to get Option, List and Map working through some simple conversions:

https://gist.github.com/mbuhot/c224f15e0266adf5ba8ca4e882f88a75

**Comment by Tarmil** [comment]
@mbuhot Thanks! I've taken some inspiration from your gist to start implementing #17.
